<a href="https://colab.research.google.com/github/raymondwcs/learning_bert/blob/master/Sentence_Embedding_in_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install --quiet transformers
from transformers import AutoModelForSequenceClassification,AutoTokenizer,BertModel,pipeline
import torch
from torch.nn.functional import cosine_similarity, pairwise_distance


In [5]:
CHECKPOINT = 'uer/roberta-base-finetuned-jd-full-chinese'  # https://huggingface.co/uer/roberta-base-finetuned-jd-full-chinese
CHECKPOINT = 'bert-base-chinese'
sentences = [
  '這個服務生很不親切',
  '这个服务生很不亲切', 
  '今天是晴天今天是晴',
  '今天是晴天',
  '今天陽光充沛!',
  '今天下大雨',     
]

tokenizer = AutoTokenizer.from_pretrained(CHECKPOINT)
model = BertModel.from_pretrained(CHECKPOINT)

tokens = tokenizer(text=sentences, add_special_tokens=True, padding=True, truncation=True, return_tensors='pt')

input_ids = tokens.input_ids[0].unsqueeze(0)
attention_mask = tokens.attention_mask[0].unsqueeze(0)
output = model(input_ids=input_ids, attention_mask=attention_mask)
sentence_embedding_01 = output.pooler_output

input_ids = tokens.input_ids[1].unsqueeze(0)
attention_mask = tokens.attention_mask[1].unsqueeze(0)
output = model(input_ids=input_ids, attention_mask=attention_mask)
sentence_embedding_02 = output.pooler_output

print(cosine_similarity(sentence_embedding_01, sentence_embedding_02))
print(pairwise_distance(sentence_embedding_01, sentence_embedding_02))

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tensor([0.9841], grad_fn=<DivBackward0>)
tensor([4.3819], grad_fn=<NormBackward1>)


In [6]:
output = model(input_ids=tokens.input_ids, output_hidden_states=True)

# https://mccormickml.com/2019/05/14/BERT-word-embeddings-tutorial/
# output[0]   # last_hidden_state
# output[1]   # pooler_output
# output[2]   # hidden layers (13 = input embeddings + 12 BERT layers)

hidden_states = output[2]

# print(hidden_states)
print(len(hidden_states))             # 13 = input embeddings + 12 BERT layers
print(hidden_states[-1].shape)        # last hidden layer [1, <input length>, 768]
print(len(hidden_states[-1]))         # 1
print(len(hidden_states[-1][0]))      # <input length>
print(len(hidden_states[-1][0][0]))   # 768
print(hidden_states[-1])

# `hidden_states` has shape [13 x 1 x <input length> x 768]
# `token_vecs` is a tensor with shape [<input length> x 768]
token_vecs = hidden_states[1:13][0]
print(len(token_vecs))

# Calculate the average of all token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)

print ("Our final sentence embedding vector of shape:", sentence_embedding.size())

13
torch.Size([6, 11, 768])
6
11
768
tensor([[[ 0.6990,  0.2976,  0.0780,  ..., -0.2679,  0.4348, -0.4079],
         [ 0.4393,  0.4274,  0.3795,  ..., -0.2055, -0.2701, -0.1704],
         [ 1.2645,  0.2934, -0.3274,  ...,  0.4628,  1.5048, -0.3984],
         ...,
         [ 0.1623,  0.5196, -0.6810,  ...,  0.9575, -0.0201,  0.4393],
         [ 0.8598,  0.1185, -0.8425,  ..., -0.4070, -0.1333, -0.1838],
         [ 0.2993,  0.5014, -0.5098,  ..., -0.5224,  0.0896, -0.0483]],

        [[ 0.9797,  0.2807, -0.0285,  ..., -0.2808,  0.6529, -0.2834],
         [ 0.3758,  0.3738,  0.4548,  ..., -0.5361,  0.0271, -0.2273],
         [ 1.1849,  0.2157, -0.3603,  ...,  0.2832,  1.6439, -0.5682],
         ...,
         [ 0.0380,  0.4457, -0.4412,  ...,  0.9437,  0.2141,  0.1889],
         [ 0.8946,  0.0085, -0.8180,  ..., -0.3052,  0.0762, -0.2281],
         [ 0.3241,  0.7086, -0.3072,  ..., -0.2152,  0.3009, -0.0885]],

        [[-0.2616,  0.3619,  0.5475,  ..., -0.0381, -0.4755,  0.3528],
        

In [7]:
tokens = tokenizer(text=sentences, add_special_tokens=True, padding=True, truncation=True, return_tensors='pt')


input_ids = tokens.input_ids[0].unsqueeze(0)
attention_mask = tokens.attention_mask[2].unsqueeze(0)
output = model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
hidden_states = output[2]
token_vecs = hidden_states[1:][0]
sentence_embedding01= torch.mean(token_vecs,dim=0)

input_ids = tokens.input_ids[1].unsqueeze(0)
attention_mask = tokens.attention_mask[1].unsqueeze(0)
output = model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
hidden_states = output[2]
token_vecs = hidden_states[1:][0]
sentence_embedding02= torch.mean(token_vecs,dim=0)

print(sentence_embedding01.size())
print(sentence_embedding02.size())

sim = cosine_similarity(sentence_embedding01, sentence_embedding02)
torch.mean(sim, dim=0)

torch.Size([11, 768])
torch.Size([11, 768])


tensor(0.9893, grad_fn=<MeanBackward1>)